### PR TITLE
Changed -no-start to --no-start in cf push

### PR DESCRIPTION
**Pull request by Freakin**
Fixed typo in CLI flag for cf push

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@Freakin Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal-cf/cf-rabbitmq-smoke-tests&pullRequestId=6)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=pivotal-cf/cf-rabbitmq-smoke-tests&pullRequestId=6) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by albertoleal** [comment]
@Freakin, thank you for your contribution.  We are closing this PR because the file changed no longer exists.  We have checked that other files correctly use `--no-start`.

Alberto and George

**Comment by pivotal-issuemaster** [comment]
@Freakin Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal-cf/cf-rabbitmq-smoke-tests&pullRequestId=6)!

**Comment by Freakin** [comment]
Thanks @albertoleal!  Moving to `workflowhelpers.NewSmokeTestSuiteSetup` should allow use of an existing space now, correct?

**Pull request closed without merging**
